const $=s=>document.querySelector(s);const app=$('#app');
const state={screen:'splash',token:localStorage.getItem('loop_token'),user:JSON.parse(localStorage.getItem('loop_user')||'null'),api:localStorage.getItem('loop_api')||location.origin,game:null,ws:null,color:null,timer:null,remaining:600000,rows:13,cols:13,settings:JSON.parse(localStorage.getItem('loop_settings')||'{"board":"13x13","sound":true,"vibrate":true}')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('loop_token',state.token||'');localStorage.setItem('loop_user',JSON.stringify(state.user||null));localStorage.setItem('loop_api',state.api);localStorage.setItem('loop_settings',JSON.stringify(state.settings));}
function toast(m){const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
async function api(path,opt={}){const r=await fetch(state.api.replace(/\/$/,'')+path,{...opt,headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token}:{}),...(opt.headers||{})}});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.error||`HTTP ${r.status}`);return d}
function shell(content,nav=true){app.innerHTML=`<main class="shell"><div class="top"><div class="brand">LOOP GAME</div>${state.user?`<span class="pill">${esc(state.user.name)}</span>`:''}</div>${content}${nav?`<div class="nav"><button data-nav="home">⌂<br>Accueil</button><button data-nav="profile">◉<br>Profil</button><button data-nav="stats">▣<br>Stats</button><button data-nav="leaderboard">★<br>Classement</button></div>`:''}</main>`;app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='home')home();if(b.dataset.nav==='profile')profile();if(b.dataset.nav==='stats')stats();if(b.dataset.nav==='leaderboard')leaderboard()})}
function splash(){app.innerHTML='<div class="splash"><div><div class="logo">LOOP</div><div class="muted">STRATEGY • 1V1 • LOOP</div><div class="loader" style="margin-top:24px"></div></div></div>';setTimeout(()=>state.token?home():login(),900)}
function login(){state.screen='login';shell(`<section class="hero center"><div class="title">Connexion</div><div class="muted">Retrouve tes parties et ton classement.</div></section><form id="login" class="card stack"><input class="input" id="email" type="email" autocomplete="email" aria-label="Email" required><input class="input" id="password" type="password" autocomplete="current-password" aria-label="Mot de passe" required><button class="btn">Se connecter</button><button type="button" class="btn secondary" id="register">Créer un compte</button></form>`,false);$('#login').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});state.token=d.token;state.user=d.user;save();home()}catch(err){toast(err.message)}};$('#register').onclick=register}
function register(){shell(`<section class="hero center"><div class="title">Créer un compte</div><div class="muted">Ton profil sera utilisé pour les parties et le classement.</div></section><form id="reg" class="card stack"><input class="input" id="name" aria-label="Pseudo" maxlength="24" required><input class="input" id="email" type="email" aria-label="Email" required><input class="input" id="password" type="password" minlength="8" aria-label="Mot de passe (8 caractères min.)" required><button class="btn">S'inscrire</button><button type="button" class="btn secondary" id="back">Retour</button></form>`,false);$('#reg').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('#name').value,email:$('#email').value,password:$('#password').value})});state.token=d.token;state.user=d.user;save();home()}catch(err){toast(err.message)}};$('#back').onclick=login}
function home(){state.screen='home';shell(`<section class="hero"><div class="pill">MATCHMAKING 1V1</div><div class="title">Prêt à fermer la boucle ?</div><div class="muted">Forme des boucles, capture les pions adverses et gagne par le score.</div></section><section class="card stack"><div class="grid2"><div><div class="muted small">Classement</div><b>${state.user?.rating??1000}</b></div><div><div class="muted small">Victoires</div><b>${state.user?.wins??0}</b></div></div><label class="muted small">Plateau</label><select class="input" id="board"><option value="13x13">13 × 13 points</option><option value="17x22">17 × 22 points</option></select><button class="btn" id="play">⚔️ Trouver un adversaire</button><button class="btn secondary" id="settings">⚙️ Paramètres</button></section>`,`true`);$('#board').value=state.settings.board;$('#play').onclick=matchmaking;$('#settings').onclick=settings}
async function matchmaking(){const [r,c]=state.settings.board.split('x').map(Number);shell(`<section class="hero center"><div class="title">Recherche d'adversaire</div><div class="loader"></div><p class="muted">Recherche 1v1 sur ${r}×${c} points…</p><button class="btn secondary" id="cancel">Annuler</button></section>`,false);let stopped=false;$('#cancel').onclick=()=>{stopped=true;home()};const poll=async()=>{if(stopped)return;try{const d=await api('/api/matchmaking/join',{method:'POST',body:JSON.stringify({rows:r,cols:c})});if(d.matched){state.color=d.color;await loadGame(d.gameId);return}setTimeout(poll,1800)}catch(e){toast(e.message);home()}};poll()}
async function loadGame(id){try{state.game=await api('/api/games/'+encodeURIComponent(id));state.rows=state.game.rows;state.cols=state.game.cols;state.remaining=state.game.timeLimit||600000;connectWS(id);renderGame()}catch(e){toast(e.message);home()}}
function connectWS(id){if(state.ws)state.ws.close();const u=new URL(state.api);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/ws';u.search='?gameId='+encodeURIComponent(id);state.ws=new WebSocket(u);state.ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='MOVE'&&m.gameId===id){state.game.stones=m.board.stones;state.game.turn=m.turn;state.game.lastMove=Date.now();if(navigator.vibrate&&state.settings.vibrate)navigator.vibrate(20);renderGame()}};state.ws.onclose=()=>{if(state.game)toast('Connexion temps réel interrompue.');}}
function boardHtml(){const cells=[];for(let r=0;r<state.rows;r++)for(let c=0;c<state.cols;c++){const k=`${r},${c}`,v=state.game.stones?.[k];cells.push(`<button class="point" data-r="${r}" data-c="${c}" aria-label="Point ${r+1},${c+1}">${v?`<span class="stone ${v==='BLUE'?'blue':'red'}"></span>`:''}</button>`)}return `<div class="board" style="grid-template-columns:repeat(${state.cols},minmax(18px,1fr));width:max-content">${cells.join('')}</div>`}
function renderGame(){const turn=state.game.turn;const mine=turn===state.color;shell(`<section class="card stack"><div class="player"><div class="avatar">${state.color==='BLUE'?'🔵':'🔴'}</div><div><b>${esc(state.user?.name||'Joueur')}</b><div class="muted">${mine?'À toi de jouer':'Tour adverse'}</div></div><div style="margin-left:auto" class="timer" id="timer">${fmt(state.remaining)}</div></div><div class="board-wrap">${boardHtml()}</div><div class="grid2"><span class="pill">🔵 Bleu</span><span class="pill">🔴 Rouge</span></div><button class="btn secondary" id="quit">Quitter la partie</button></section>`,false);app.querySelectorAll('.point').forEach(b=>b.onclick=()=>move(+b.dataset.r,+b.dataset.c));$('#quit').onclick=()=>{state.ws?.close();state.game=null;home()};clearInterval(state.timer);state.timer=setInterval(()=>{if(state.game?.turn===state.color){state.remaining=Math.max(0,state.remaining-1000);const t=$('#timer');if(t)t.textContent=fmt(state.remaining);if(!state.remaining){clearInterval(state.timer);results()}}},1000)}
async function move(r,c){if(!state.game||state.game.turn!==state.color)return toast('Ce n’est pas ton tour.');try{const d=await api('/api/games/'+state.game.id+'/move',{method:'POST',body:JSON.stringify({point:{r,c}})});state.game.stones=d.board.stones;state.game.turn=d.turn;renderGame();if(d.capturedCount)toast(`Capture : ${d.capturedCount} pion(s)`)}catch(e){toast(e.message)}}
function fmt(ms){const s=Math.ceil(ms/1000),m=Math.floor(s/60),x=s%60;return `${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function results(){clearInterval(state.timer);shell(`<section class="hero center"><div class="title">Fin de partie</div><p class="muted">Le temps est écoulé.</p></section><section class="card stack"><div class="stat"><span>Ton score</span><b>${state.user?.points??0}</b></div><button class="btn" id="again">Rejouer</button><button class="btn secondary" id="home">Accueil</button></section>`,false);$('#again').onclick=matchmaking;$('#home').onclick=home}
async function profile(){try{state.user=await api('/api/me');save()}catch{}shell(`<section class="hero"><div class="player"><div class="avatar">🎴</div><div><div class="title" style="font-size:25px">${esc(state.user?.name||'Joueur')}</div><span class="pill">Rating ${state.user?.rating??1000}</span></div></div></section><section class="card"><div class="stat"><span>Victoires</span><b>${state.user?.wins??0}</b></div><div class="stat"><span>Défaites</span><b>${state.user?.losses??0}</b></div><div class="stat"><span>Captures</span><b>${state.user?.captures??0}</b></div><div class="stat"><span>Points</span><b>${state.user?.points??0}</b></div></section><button class="btn danger" id="logout" style="margin-top:12px">Se déconnecter</button>`,true);$('#logout').onclick=()=>{state.token=null;state.user=null;save();login()}}
async function stats(){await profileStats('stats')}
async function profileStats(mode){try{state.user=await api('/api/me');save()}catch{}shell(`<section class="hero"><div class="title">Statistiques</div><div class="muted">Progression de ton profil.</div></section><section class="card"><div class="grid2"><div><div class="muted small">Rating</div><div class="title" style="font-size:25px">${state.user?.rating??1000}</div></div><div><div class="muted small">Points</div><div class="title" style="font-size:25px">${state.user?.points??0}</div></div></div><div class="stat"><span>Parties gagnées</span><b>${state.user?.wins??0}</b></div><div class="stat"><span>Parties perdues</span><b>${state.user?.losses??0}</b></div><div class="stat"><span>Captures</span><b>${state.user?.captures??0}</b></div></section>`,true)}
async function leaderboard(){try{const rows=await api('/api/leaderboard');shell(`<section class="hero"><div class="title">Classement mondial</div><div class="muted">Les meilleurs joueurs en temps réel.</div></section><section class="card">${rows.map((u,i)=>`<div class="rank"><b>#${i+1}</b><div><b>${esc(u.name)}</b><div class="muted small">${u.wins} V • ${u.captures} captures</div></div><strong>${u.rating}</strong></div>`).join('')}</section>`,true)}catch(e){toast(e.message)}}
function settings(){shell(`<section class="hero"><div class="title">Paramètres</div></section><section class="card stack"><label class="muted small">Serveur API</label><input class="input" id="api" value="${esc(state.api)}"><label class="muted small">Plateau préféré</label><select class="input" id="board"><option value="13x13">13 × 13 points</option><option value="17x22">17 × 22 points</option></select><label><input type="checkbox" id="sound" ${state.settings.sound?'checked':''}> Sons</label><label><input type="checkbox" id="vibrate" ${state.settings.vibrate?'checked':''}> Vibrations</label><button class="btn" id="saveSet">Enregistrer</button><button class="btn secondary" id="backHome">Retour</button></section>`,true);$('#board').value=state.settings.board;$('#saveSet').onclick=()=>{state.api=$('#api').value.replace(/\/$/,'');state.settings.board=$('#board').value;state.settings.sound=$('#sound').checked;state.settings.vibrate=$('#vibrate').checked;save();toast('Paramètres enregistrés');home()};$('#backHome').onclick=home}
window.addEventListener('load',()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});splash()});
